version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://snackoverflow.local
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=1234
      - DB_DATABASE=bookstackapp
      - MAIL_DRIVER=smtp

      # Host, Port & Encryption mechanism to use
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_ENCRYPTION=tls

      # Authentication details for your SMTP service
      #- MAIL_USERNAME=mymail@mydomain.com
      #- MAIL_PASSWORD=<mailpass>

      # The "from" email address for outgoing email
      #- MAIL_FROM=fromaddress@mydomain.com

      # The "from" name used for outgoing email
      #- MAIL_FROM_NAME=My wiki
    volumes:
      - ./config:/config
    ports:
      - 80:80
    depends_on:
      - bookstack_db
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=1234
    volumes:
      - ./db:/config
